import { Inter } from "next/font/google";
import "./globals.css";
import { AI } from "./api/action";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <AI>
        <body className={inter.className}>{children}</body>
      </AI>
    </html>
  );
}
